### ISSUE TITLE
Exception loading Idea 2019.2

### ISSUE THREAD

**Issue by marek-parfianowicz** [openclover/clover#106]
ntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019

Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1965M
Cores: 8
Registry:
Non-Bundled Plugins: CopyRestUrl, com.github.kisstkondoros.codemetrics, com.linsage, com.remoterapp.adbremote.jsonviewer.id, com.viartemev.requestmapper, LivePlugin, com.itangcent.idea.plugin.easy-api, dev.vinayshetty.stateart, com.intellij.plugins.html.instantEditing, com.zhaow.restful.toolkit, org.openclover.idea

java.lang.NullPointerException
at com.atlassian.clover.idea.coverageview.CoverageViewPanel.initListeners(CoverageViewPanel.java:131)
at com.atlassian.clover.idea.coverageview.CoverageViewPanel.<init>(CoverageViewPanel.java:103)

**Comment by marek-parfianowicz** [comment]
Duplicate of #109.

**Comment by marek-parfianowicz** [comment]
Original report: https://bitbucket.org/openclover/clover/issues/106
