### ISSUE TITLE
HTML Reporter throwing null pointer error (NPE) - Mac (Catlaina: 10.15.3)

### ISSUE THREAD

**Issue by DSEyers** [openclover/clover#122]
Can you look at this issue please:
https://github.com/bmuschko/gradle-clover-plugin/issues/146

Apparently the issue is with OpenCloser ;(

**Comment by JasonWThompson** [comment]
I think it has to do with https://github.com/openclover/clover/blob/c3729a8251787ea550b45260270d5cb48cb8f0f9/clover-core/src/main/java/com/atlassian/clover/reporters/html/RenderFileAction.java#L111

Here the code is attempting to get a value out of ThreadLocal object. I suspect that for one reason or another, either initThreadLocals is not being called or resetThreadLocals is being called before RenderFileAction.call

In any case, it's super irritating and breaking my builds in Jenkins. Though my build seem to work on my local device.

```
[INFO] Writing HTML report to '/home/jenkins/jenkins/workspace/mmf-cps-storage-content/target/site/clover'
[WARNING] null
java.lang.NullPointerException
    at com.atlassian.clover.reporters.html.RenderFileAction.call (RenderFileAction.java:111)
    at com.atlassian.clover.util.CloverExecutors$LoggingCallable.call (CloverExecutors.java:91)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
```

**Comment by n-hebert** [comment]
Hello,

We're also experiencing this issue breaking builds on our Jenkins due to OpenClover.

It only seems to occur if we run partial tests (skip certain folders, classes, etc.), but if I do I see it on Jenkins, locally, and in GitLab Pipelines. Ergo it occurs on any clean workspace.

Is this potentially due to OpenClover expecting all classes in sight to be executed as tests?

**Comment by marek-parfianowicz** [comment]
I've investigated this against OpenClover 5.0.0, and I think this ticket currently holds **two unrelated bugs**. Let me separate them.

### 1. The original report (JFreeChart NPE on macOS)

The linked `bmuschko/gradle-clover-plugin#146` fails in JFreeChart:

```
java.lang.NullPointerException
    at clover.org.jfree.chart.axis.ValueAxis.findMaximumTickLabelWidth(ValueAxis.java:916)
```

This is a chart/font-metrics problem (headless AWT on Catalina), and is unrelated to the stack traces @JasonWThompson and @n-hebert posted below it.

### 2. The `RenderFileAction` NPE 

```
java.lang.NullPointerException
    at ...reporters.html.RenderFileAction.call(RenderFileAction.java:111)
    at ...util.CloverExecutors$LoggingCallable.call(CloverExecutors.java:91)
```

**This is still reproducible on 5.0.0.** @JasonWThompson's diagnosis was correct. The details:

`RenderFileAction` holds its column/context state in two **static** fields:

```java
protected static ThreadLocal<List<Column>> columnsTL;
protected static ThreadLocal<ContextSet> contextSetTL;
```

but their lifecycle is owned by `HtmlReporter`, which calls `initThreadLocals()` before submitting render tasks and `resetThreadLocals()` in a `finally` block — and that reset assigns the statics back to `null`. 

I've reproduced this with a unit test on the 5.0.x branch.

**Fix direction:** make this state per-report rather than static, so each `HtmlReporter` owns its own lifecycle and one report's cleanup can't affect another's in-flight tasks. Additionally, the `finally` reset shouldn't run while tasks may still be executing.

### On the Jenkins angle

For those arriving here from the Jenkins Clover Plugin: this NPE does **not** originate in the plugin. The plugin only parses `clover.xml` and copies the already-generated HTML report directory; it never invokes `HtmlReporter`. The failure happens in the Maven/Ant JVM that generates the report, upstream of the plugin, so the plugin version is not a factor.

### Proposal

I'd like to keep this ticket for the original JFreeChart/macOS NPE and split the `RenderFileAction` issue into its own ticket, since they need separate fixes. Any objections?

**Comment by marek-parfianowicz** [comment]
FYI I created https://github.com/openclover/clover/issues/304 to track RenderFileAction
