### ISSUE TITLE
OpenClover plugin for idea throws an IDE fatal error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by gweii** [openclover/clover#124]
After idea 2019.3.4 opens my project, it throws this exception:

java.lang.NullPointerException
	at com.atlassian.clover.idea.coverageview.CoverageViewPanel.initListeners(CoverageViewPanel.java:131)
	at com.atlassian.clover.idea.coverageview.CoverageViewPanel.<init>(CoverageViewPanel.java:103)
	at com.atlassian.clover.idea.CloverToolWindow.getCoveragePane(CloverToolWindow.java:184)
	at com.atlassian.clover.idea.CloverToolWindow.initComponents(CloverToolWindow.java:113)
	at com.atlassian.clover.idea.CloverToolWindow.<init>(CloverToolWindow.java:68)
	at com.atlassian.clover.idea.CloverToolWindow.getInstance(CloverToolWindow.java:58)
	at com.atlassian.clover.idea.ProjectPlugin.projectPostStartup(ProjectPlugin.java:113)
	at com.atlassian.clover.idea.ProjectPlugin$1.run(ProjectPlugin.java:75)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:454)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.lambda$run$0(StartupManagerImpl.java:279)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:247)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$6(StartupManagerImpl.java:486)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:324)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:472)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:239)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:279)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:396)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:388)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:68)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
![IDE_Fatal_Errors](https://user-images.githubusercontent.com/32036273/78753946-3f7fde80-79a9-11ea-8f07-980ec9475f66.jpg)

**Comment by gweii** [comment]
this bug is reported already:

https://bitbucket.org/openclover/clover/issues/108/exception-throws-at-intellij-launch
