### ISSUE TITLE
OC-41 Unit test failure

### ISSUE THREAD

**Issue by marek-parfianowicz** [openclover/clover#41]
I'm experiencing an issue with 1 unit test in my code base.

An exception has occurred in the compiler (1.8.0_152). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.

`java.lang.AssertionError
    at com.sun.tools.javac.util.Assert.error(Assert.java:126)
    at com.sun.tools.javac.util.Assert.check(Assert.java:45)
    at com.sun.tools.javac.code.SymbolMetadata.setDeclarationAttributesWithCompletion(SymbolMetadata.java:161)
    at com.sun.tools.javac.code.Symbol.setDeclarationAttributesWithCompletion(Symbol.java:215)
    at com.sun.tools.javac.comp.MemberEnter.actualEnterAnnotations(MemberEnter.java:952)
    at com.sun.tools.javac.comp.MemberEnter.access$600(MemberEnter.java:64)
    at com.sun.tools.javac.comp.MemberEnter$5.run(MemberEnter.java:876)
    at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:143)
    at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:129)
    at com.sun.tools.javac.comp.Enter.complete(Enter.java:512)
    at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
    at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:857)
    at com.sun.tools.javac.main.Main.compile(Main.java:523)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
    at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1075)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:168)`

I'm running the following:

MacOS High Sierra
JDK 8 Update 152
Maven 3.5.2
Openclover 4.2.1
I have been running the plugin like this with:

`mvn clover:clean clover:instrument clover:aggregate clover:clover`

and that runs fine.

**Comment by marek-parfianowicz** [comment]
Original report: https://bitbucket.org/openclover/clover/issues/41

**Comment by marek-parfianowicz** [comment]
No code sample, not reproducible.
