### ISSUE TITLE
NullPointerException in InstrumentInternal

### ISSUE THREAD

**Issue by marek-parfianowicz** [openclover/clover#60]
I have a multi-module maven project. This is my plugin setup. I took this directly from the integration tests.

         <plugin>
            <groupId>org.openclover</groupId>
            <artifactId>clover-maven-plugin</artifactId>
            <version>4.2.1</version>
            <configuration>
               <includesTestSourceRoots>true</includesTestSourceRoots>
            </configuration>
            <executions>
               <execution>
                  <id>site</id>
                  <phase>pre-site</phase>
                  <goals>
                     <goal>instrument</goal>
                     <goal>aggregate</goal>
                     <goal>save-history</goal>
                  </goals>
               </execution>
               <execution>
                  <id>main</id>
                  <phase>verify</phase>
                  <goals>
                     <goal>instrument</goal>
                     <goal>aggregate</goal>
                     <goal>check</goal>
                     <goal>log</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
I am getting the following exception.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clover-plugin:2.4:instrumentInternal (default-cli) on project rest-clients: Execution default-cli of goal org.apache.maven.plugins:maven-clover-plugin:2.4:instrumentInternal failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-clover-plugin:2.4:instrumentInternal (default-cli) on project rest-clients: Execution default-cli of goal org.apache.maven.plugins:maven-clover-plugin:2.4:instrumentInternal failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-clover-plugin:2.4:instrumentInternal failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 24 more
Caused by: java.lang.NullPointerException
    at org.apache.maven.plugin.clover.internal.AbstractCloverMojo.registerLicenseFile(AbstractCloverMojo.java:169)
    at org.apache.maven.plugin.clover.internal.AbstractCloverMojo.registerLicenseFile(AbstractCloverMojo.java:134)
    at org.apache.maven.plugin.clover.internal.AbstractCloverMojo.execute(AbstractCloverMojo.java:119)
    at org.apache.maven.plugin.clover.CloverInstrumentInternalMojo.execute(CloverInstrumentInternalMojo.java:132)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 25 more
I am trying to:

Check coverage against set level.
Save a report of the coverage.
Keep a historical list of coverage

**Comment by marek-parfianowicz** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clover-plugin:2.4:instrumentInternal

You are running very old maven-clover-plugin version 2.4 from the org.apache.maven.plugins groupId instead of the clover-maven-plugin 4.2.1 from org.openclover groupId.

Check if you have the org.openclover defined in settings.xml, see http://openclover.org/doc/manual/4.2.0/maven--quick-start-guide.html

**Comment by marek-parfianowicz** [comment]
Original report: https://bitbucket.org/openclover/clover/issues/60
