### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by marek-parfianowicz** [openclover/clover#66]
Kris M created an issue 2018-04-24
Multimodule project

17:33:36 Apache Maven 3.5.0 17:33:36 Java version: 1.8.0_51, vendor: Oracle Corporation

[ERROR] Failed to execute goal org.openclover:clover-maven-plugin:4.2.1:setup (default-cli) on project ...... Failed to execute goal org.openclover:clover-maven-plugin:4.2.1:setup (default-cli) on project submodule-name-here: Execution default-cli of goal org.openclover:clover-maven-plugin:4.2.1:setup failed.

17:33:44 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213) 17:33:44 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154) 17:33:44 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146) 17:33:44 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117) 17:33:44 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81) 17:33:44 at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) 17:33:44 at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) 17:33:44 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309) 17:33:44 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194) 17:33:44 at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107) 17:33:44 at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993) 17:33:44 at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345) 17:33:44 at org.apache.maven.cli.MavenCli.main(MavenCli.java:191) 17:33:44 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 17:33:44 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 17:33:44 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 17:33:44 at java.lang.reflect.Method.invoke(Method.java:497) 17:33:44 at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) 17:33:44 at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) 17:33:44 at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) 17:33:44 at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) 17:33:44 Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.openclover:clover-maven-plugin:4.2.1:setup failed. 17:33:44 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145) 17:33:44 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) 17:33:44 ... 20 more 17:33:44 Caused by: java.lang.NullPointerException 17:33:44 at com.atlassian.maven.plugin.clover.CloverInstrumentInternalMojo.swizzleCloverDependencies(CloverInstrumentInternalMojo.java:533) 17:33:44 at com.atlassian.maven.plugin.clover.CloverInstrumentInternalMojo.swizzleCloverDependencies(CloverInstrumentInternalMojo.java:491) 17:33:44 at com.atlassian.maven.plugin.clover.CloverInstrumentInternalMojo.execute(CloverInstrumentInternalMojo.java:299) 17:33:44 at com.atlassian.maven.plugin.clover.CloverSetupMojo.execute(CloverSetupMojo.java:31) 17:33:44 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) 17:33:44 ... 21 more

**Comment by marek-parfianowicz** [comment]
Original report: https://bitbucket.org/openclover/clover/issues/66
